version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: pgdb
    environment:
      POSTGRES_USER: iotuser
      POSTGRES_PASSWORD: iotpass
      POSTGRES_DB: iotdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
      - mqtt
    environment:
      - PGUSER=iotuser
      - PGPASSWORD=iotpass
      - PGDATABASE=iotdata
      - PGHOST=db
      - MQTT_BROKER=mqtt://mqtt_broker:1883
    ports:
      - "3000:3000"

volumes:
  pgdata: